name: true_size
description: A comprehensive size and measurement tracking app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Stacked Architecture
  stacked: ^3.4.0
  stacked_services: ^1.2.0

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.6

  # Responsive Design
  responsive_builder: ^0.7.0

  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # State Management & Navigation
  get_it: ^7.6.4
  auto_route: ^7.8.4

  # Utilities
  uuid: ^4.2.1
  intl: ^0.18.1

  # Development
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  stacked_generator: ^1.5.0
  auto_route_generator: ^7.3.2
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/