name: true_size
description: A comprehensive size and measurement tracking app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Stacked Architecture
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  sizer: ^3.0.5
#  stacked_themes: ^0.3.15
  stacked_hooks: ^0.2.5
  #stacked_themes: ^0.3.15

  # Responsive Design
  responsive_builder: ^0.7.0

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.0.3
  google_sign_in: ^7.2.0



  # UI Components
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  hugeicons: ^0.0.12
  flex_color_scheme: ^8.3.0
  google_fonts: ^6.2.1

  # State Management & Navigation
  get_it: ^8.2.0
  auto_route: ^7.9.2

  # Utilities
  uuid: ^4.5.1

  intl: ^0.20.2

  # Development
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.1
  stacked_generator: ^1.5.1
  auto_route_generator: ^7.3.2
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/